DB_NAME = "db"
USER_COLLECTION_NAME = 'users'
DELI_COLLECTION_NAME = "delis"
COLD_DELI_COLLECTION_NAME = "colddelis"
HOT_DELI_COLLECTION_NAME = "hotdelis"
DELISET_COLLECTION_NAME = "delisets"
ORDER_COLLECTION_NAME = "orders"